alias r='source ~/.Bothrc.sh'
alias TreeN='cd "$(TreeFolder)" && n'
alias mpv='mpv --save-position-on-quit'
alias TAM='tmux new -s $$ -D -t'
alias DOOM='cd /home/zaki/Doom && gzdoom brutalv21.pk3'
alias td='todo.sh'
alias tdm='todotxt-machine'
alias npv='mpv --no-video'
alias KK='kitty +kitten'
alias info='info --vi-keys'
alias mount='sudo mount'
alias umount='sudo umount'
alias make='sudo make'
alias NOTES='cd /home/zaki/Wiki/Notes && vim /home/zaki/Wiki/Notes/ProgramList.otl /home/zaki/Wiki/Notes/Ideas.md /home/zaki/Wiki/Notes/BigTodo.otl -p'
alias hc='herbstclient "$@"'
alias rp='ratpoison -c '
alias LB='libreoffice --headless --convert-to '
alias s='sudo '
alias sp='sudo pacman'
alias TMP='cd $(mktemp -d)'
alias CTA='compton-trans -c -o '
alias Dvim="vim -u NONE"
alias CTM='compton-trans -o '
alias CRS='pkill compton 
compton & disown'
alias PINK='mpv --no-video "https://www.youtube.com/watch?v=6D7IZQzCqNk&t=946s"'
alias VIMMMIN='vim -u NONE -U NONE -N -i NONE'
alias EList='ls "${TMPDIR-/tmp}/emacs$(id -u)"'
alias fbreader='FBReader'
alias Mang='
cd /home/zaki/Wiki/Conf/Mang/Scripts/
tmux new -s Mang './TmuxSetup.sh'
tmux attach
'


alias rm='trash'
alias t='tree'
alias TreeMpv='mpv "$(/bin/tree  -fQP "*.m4v\|.mkv\|*.mp3\|*.mp4"  | fzy | sed "s/\W*//" | sed "s/\"//")" '
alias cdt='/bin/tree ~/ -fdQ  | fzy | sed "s/\W*//" | sed "s/\"//" '

alias ls="ls -h --color=auto"
alias less='less -r'
alias Tree='tree -C'
alias p='sudo pacman'
alias y='yay -S'
alias grep='grep -n --color=always'
alias vifm='vifm .'
alias gc='gcalcli'
alias bat='acpi'
alias XC='echo $(pwd)/| xclip'
alias srd='sr -browser=w3m duckduckgo'
alias sra='sr -browser=w3m aur'
alias sqd='sr -browser=qutebrowser duckduckgo'
alias ssd='sr -browser=surf duckduckgo'
alias svd='sr -browser=vimb duckduckgo'
alias srp='sr -browser=w3m piratebay'
alias sry='sr -browser=w3m youtube'
alias srg='sr -browser=w3m $1'
alias dff='df -hT -t ext4'
#alias yay=''
#alias pacman=''
alias LU='/bin/qutebrowser $1'
alias VWP='mpv --wid 0 $1'
alias vv='vit -CCONF'
alias n='nnn'
alias f='fff'
alias vf='vifm'
alias rf='ranger'
alias SW='mpv "$(ls | fzy)"'
alias OFF='mpv --no-input-default-bindings $(ls | fzy)'
alias vid='vim $(ls * | fzy)'
alias config='/usr/bin/git --git-dir=/home/zaki/.DotFiles/ --work-tree=/home/zaki'
